/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BottomBar {
    }
    interface MsgPage {
    }
    interface NavbarElem {
        "onclickProp": string;
    }
    interface SideBar {
    }
}
declare global {
    interface HTMLBottomBarElement extends Components.BottomBar, HTMLStencilElement {
    }
    var HTMLBottomBarElement: {
        prototype: HTMLBottomBarElement;
        new (): HTMLBottomBarElement;
    };
    interface HTMLMsgPageElement extends Components.MsgPage, HTMLStencilElement {
    }
    var HTMLMsgPageElement: {
        prototype: HTMLMsgPageElement;
        new (): HTMLMsgPageElement;
    };
    interface HTMLNavbarElemElement extends Components.NavbarElem, HTMLStencilElement {
    }
    var HTMLNavbarElemElement: {
        prototype: HTMLNavbarElemElement;
        new (): HTMLNavbarElemElement;
    };
    interface HTMLSideBarElement extends Components.SideBar, HTMLStencilElement {
    }
    var HTMLSideBarElement: {
        prototype: HTMLSideBarElement;
        new (): HTMLSideBarElement;
    };
    interface HTMLElementTagNameMap {
        "bottom-bar": HTMLBottomBarElement;
        "msg-page": HTMLMsgPageElement;
        "navbar-elem": HTMLNavbarElemElement;
        "side-bar": HTMLSideBarElement;
    }
}
declare namespace LocalJSX {
    interface BottomBar {
    }
    interface MsgPage {
    }
    interface NavbarElem {
        "onclickProp"?: string;
    }
    interface SideBar {
    }
    interface IntrinsicElements {
        "bottom-bar": BottomBar;
        "msg-page": MsgPage;
        "navbar-elem": NavbarElem;
        "side-bar": SideBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bottom-bar": LocalJSX.BottomBar & JSXBase.HTMLAttributes<HTMLBottomBarElement>;
            "msg-page": LocalJSX.MsgPage & JSXBase.HTMLAttributes<HTMLMsgPageElement>;
            "navbar-elem": LocalJSX.NavbarElem & JSXBase.HTMLAttributes<HTMLNavbarElemElement>;
            "side-bar": LocalJSX.SideBar & JSXBase.HTMLAttributes<HTMLSideBarElement>;
        }
    }
}
