/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BottomBar {
    }
    interface HomePost {
        "hpBild": string;
        "hpDesc": string;
        "hpName": string;
        "hpPost": string;
    }
    interface LikePage {
        "likeName": string;
        "likeType": string;
    }
    interface MsgPage {
    }
    interface NavbarElem {
        "onclickProp": string;
    }
    interface PostMenu {
    }
    interface SearchBar {
    }
    interface SharePost {
    }
    interface SideBar {
    }
    interface UserPage {
        "upBild": string;
        "upDesc": string;
        "upName": string;
    }
}
declare global {
    interface HTMLBottomBarElement extends Components.BottomBar, HTMLStencilElement {
    }
    var HTMLBottomBarElement: {
        prototype: HTMLBottomBarElement;
        new (): HTMLBottomBarElement;
    };
    interface HTMLHomePostElement extends Components.HomePost, HTMLStencilElement {
    }
    var HTMLHomePostElement: {
        prototype: HTMLHomePostElement;
        new (): HTMLHomePostElement;
    };
    interface HTMLLikePageElement extends Components.LikePage, HTMLStencilElement {
    }
    var HTMLLikePageElement: {
        prototype: HTMLLikePageElement;
        new (): HTMLLikePageElement;
    };
    interface HTMLMsgPageElement extends Components.MsgPage, HTMLStencilElement {
    }
    var HTMLMsgPageElement: {
        prototype: HTMLMsgPageElement;
        new (): HTMLMsgPageElement;
    };
    interface HTMLNavbarElemElement extends Components.NavbarElem, HTMLStencilElement {
    }
    var HTMLNavbarElemElement: {
        prototype: HTMLNavbarElemElement;
        new (): HTMLNavbarElemElement;
    };
    interface HTMLPostMenuElement extends Components.PostMenu, HTMLStencilElement {
    }
    var HTMLPostMenuElement: {
        prototype: HTMLPostMenuElement;
        new (): HTMLPostMenuElement;
    };
    interface HTMLSearchBarElement extends Components.SearchBar, HTMLStencilElement {
    }
    var HTMLSearchBarElement: {
        prototype: HTMLSearchBarElement;
        new (): HTMLSearchBarElement;
    };
    interface HTMLSharePostElement extends Components.SharePost, HTMLStencilElement {
    }
    var HTMLSharePostElement: {
        prototype: HTMLSharePostElement;
        new (): HTMLSharePostElement;
    };
    interface HTMLSideBarElement extends Components.SideBar, HTMLStencilElement {
    }
    var HTMLSideBarElement: {
        prototype: HTMLSideBarElement;
        new (): HTMLSideBarElement;
    };
    interface HTMLUserPageElement extends Components.UserPage, HTMLStencilElement {
    }
    var HTMLUserPageElement: {
        prototype: HTMLUserPageElement;
        new (): HTMLUserPageElement;
    };
    interface HTMLElementTagNameMap {
        "bottom-bar": HTMLBottomBarElement;
        "home-post": HTMLHomePostElement;
        "like-page": HTMLLikePageElement;
        "msg-page": HTMLMsgPageElement;
        "navbar-elem": HTMLNavbarElemElement;
        "post-menu": HTMLPostMenuElement;
        "search-bar": HTMLSearchBarElement;
        "share-post": HTMLSharePostElement;
        "side-bar": HTMLSideBarElement;
        "user-page": HTMLUserPageElement;
    }
}
declare namespace LocalJSX {
    interface BottomBar {
    }
    interface HomePost {
        "hpBild"?: string;
        "hpDesc"?: string;
        "hpName"?: string;
        "hpPost"?: string;
        "onExampleEvent"?: (event: CustomEvent<string>) => void;
    }
    interface LikePage {
        "likeName"?: string;
        "likeType"?: string;
    }
    interface MsgPage {
    }
    interface NavbarElem {
        "onclickProp"?: string;
    }
    interface PostMenu {
    }
    interface SearchBar {
    }
    interface SharePost {
    }
    interface SideBar {
    }
    interface UserPage {
        "upBild"?: string;
        "upDesc"?: string;
        "upName"?: string;
    }
    interface IntrinsicElements {
        "bottom-bar": BottomBar;
        "home-post": HomePost;
        "like-page": LikePage;
        "msg-page": MsgPage;
        "navbar-elem": NavbarElem;
        "post-menu": PostMenu;
        "search-bar": SearchBar;
        "share-post": SharePost;
        "side-bar": SideBar;
        "user-page": UserPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bottom-bar": LocalJSX.BottomBar & JSXBase.HTMLAttributes<HTMLBottomBarElement>;
            "home-post": LocalJSX.HomePost & JSXBase.HTMLAttributes<HTMLHomePostElement>;
            "like-page": LocalJSX.LikePage & JSXBase.HTMLAttributes<HTMLLikePageElement>;
            "msg-page": LocalJSX.MsgPage & JSXBase.HTMLAttributes<HTMLMsgPageElement>;
            "navbar-elem": LocalJSX.NavbarElem & JSXBase.HTMLAttributes<HTMLNavbarElemElement>;
            "post-menu": LocalJSX.PostMenu & JSXBase.HTMLAttributes<HTMLPostMenuElement>;
            "search-bar": LocalJSX.SearchBar & JSXBase.HTMLAttributes<HTMLSearchBarElement>;
            "share-post": LocalJSX.SharePost & JSXBase.HTMLAttributes<HTMLSharePostElement>;
            "side-bar": LocalJSX.SideBar & JSXBase.HTMLAttributes<HTMLSideBarElement>;
            "user-page": LocalJSX.UserPage & JSXBase.HTMLAttributes<HTMLUserPageElement>;
        }
    }
}
